export const FETCH_BANKS_DATA = "FETCH_BANKS_DATA";
export const SAVE_BANKS_DATA = "SAVE_BANKS_DATA";
export const ADD_FAVORITE_BANK = "ADD_FAVORITE_BANK";
export const REMOVE_FAVORITE_BANK = "REMOVE_FAVORITE_BANK";